#!/usr/bin/with-contenv bash
# to make NAMESPACE & NOTEBOOK_NAME available when running the image
echo "NAMESPACE=\$(echo \$NB_PREFIX | awk -F '/' '{print \$3}')" >> /etc/profile
echo "NOTEBOOK_NAME=\$(echo \$NB_PREFIX | awk -F '/' '{print \$4}')" >> /etc/profile

echo "NAMESPACE=\$(echo \$NB_PREFIX | awk -F '/' '{print \$3}')" >> ~/.bashrc
echo "NOTEBOOK_NAME=\$(echo \$NB_PREFIX | awk -F '/' '{print \$4}')" >> ~/.bashrc
